routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ZoneController;
use App\Http\Controllers\TourController;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\DepartureController;
use App\Http\Controllers\CommissionController;
use App\Http\Controllers\ReservationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::group(['middleware' => 'auth'], function() {
    ///====================================================
    /// Users Routing
    ///====================================================
    Route::get('/users/create', [ UserController::class, 'create'])->name('users.create');
    Route::get('/users/reservations', [ UserController::class, 'reservations'])->name('users.reservations');
    Route::get('/users/{user}/reservations', [ UserController::class, 'userReservations'])->name('users.single.reservations');
    Route::get('/users', [ UserController::class, 'index' ])->name('users.index');
    Route::get('/users/{user}', [ UserController::class, 'show' ])->name('users.show');
    Route::get('/users/{user}/profile', [ UserController::class, 'profile' ])->name('users.profile');
    Route::put('/users/{user}/profile', [ UserController::class, 'updateProfile'])->name('users.update.profile');
    Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::post('/users', [ UserController::class, 'store'])->name('users.store');
    Route::delete('/users/{user}', [ UserController::class, 'destroy'])->name('users.destroy');

    ///====================================================
    /// Roles Routing
    ///====================================================
    Route::get('/roles', [ RoleController::class, 'index'])->name('roles.index');
    Route::get('/roles/create', [ RoleController::class, 'create'])->name('roles.create');
    Route::post('/roles', [ RoleController::class, 'store'])->name('roles.store');
    Route::get('/roles/{role}', [ RoleController::class, 'show'])->name('roles.show');
    Route::get('/roles/{role}/edit', [ RoleController::class, 'edit'])->name('roles.edit');
    Route::put('/roles/{role}', [ RoleController::class, 'update'])->name('roles.update');
    Route::delete('/roles/{role}', [ RoleController::class, 'destroy'])->name('roles.destroy');

    ///====================================================
    /// Roles Routing
    ///====================================================
    Route::get('/zones', [ ZoneController::class, 'index'])->name('zones.index');
    Route::get('/zones/create', [ ZoneController::class, 'create'])->name('zones.create');
    Route::post('/zones', [ ZoneController::class, 'store'])->name('zones.store');
    Route::get('/zones/{zone}', [ ZoneController::class, 'show'])->name('zones.show');
    Route::get('/zones/{zone}/edit', [ ZoneController::class, 'edit'])->name('zones.edit');
    Route::put('/zones/{zone}', [ ZoneController::class, 'update'])->name('zones.update');
    Route::delete('/zones/{zone}', [ ZoneController::class, 'destroy'])->name('zones.destroy');

    ///====================================================
    /// Hotels Routing
    ///====================================================
    Route::get('/hotels', [ HotelController::class, 'index'])->name('hotels.index');
    Route::get('/hotels/create', [ HotelController::class, 'create'])->name('hotels.create');
    Route::post('/hotels', [ HotelController::class, 'store'])->name('hotels.store');
    Route::get('/hotels/{hotel}', [ HotelController::class, 'show'])->name('hotels.show');
    Route::get('/hotels/{hotel}/edit', [ HotelController::class, 'edit'])->name('hotels.edit');
    Route::put('/hotels/{hotel}', [ HotelController::class, 'update'])->name('hotels.update');
    Route::delete('/hotels/{hotel}', [ HotelController::class, 'destroy'])->name('hotels.destroy');

    ///====================================================
    /// Tours Routing
    ///====================================================
    Route::get('/tours', [ TourController::class, 'index'])->name('tours.index');
    Route::get('/tours/create', [ TourController::class, 'create'])->name('tours.create');
    Route::post('/tours', [ TourController::class, 'store'])->name('tours.store');
    Route::get('/tours/{tour}', [ TourController::class, 'show'])->name('tours.show');
    Route::get('/tours/{tour}/edit', [ TourController::class, 'edit'])->name('tours.edit');
    Route::put('/tours/{tour}', [ TourController::class, 'update'])->name('tours.update');
    Route::delete('/tours/{tour}', [ TourController::class, 'destroy'])->name('tours.destroy');

    ///====================================================
    /// Commissions Routing
    ///====================================================
    Route::get('/commissions/create/{user}', [ CommissionController::class, 'create'])->name('commissions.create');
    Route::post('/commissions', [ CommissionController::class, 'store'])->name('commissions.store');
    Route::get('/commissions/{commission}/edit', [ CommissionController::class, 'edit'])->name('commissions.edit');
    Route::put('/commissions/{commission}', [ CommissionController::class, 'update'])->name('commissions.update');
    Route::delete('/commissions/{commission}', [ CommissionController::class, 'destroy'])->name('commissions.destroy');

    ///====================================================
    /// Commissions Routing
    ///====================================================
    Route::get('/departures/create', [ DepartureController::class, 'create'])->name('departures.create');
    Route::post('/departures', [ DepartureController::class, 'store'])->name('departures.store');
    Route::get('/departures/{departure}/edit', [ DepartureController::class, 'edit'])->name('departures.edit');
    Route::put('/departures/{departure}', [ DepartureController::class, 'update'])->name('departures.update');
    Route::get('/departures/close', [ DepartureController::class, 'close'])->name('departures.close');
    Route::delete('/departures/{departure}', [ DepartureController::class, 'destroy'])->name('departures.destroy');

    ///====================================================
    /// Reservatiosn Routing
    ///====================================================
    Route::get('/reservations', [ ReservationController::class, 'index'])->name('reservations.index');
    Route::get('/reservations/select_tour', [ ReservationController::class, 'selectTour' ])->name('reservations.select.tour');
    Route::get('/reservations/create', [ ReservationController::class, 'create'])->name('reservations.create');
    Route::get('/reservations/create/select_seats', [ ReservationController::class, 'selectSeats' ])->name('reservations.create.select.seats');
    Route::post('/reservations', [ ReservationController::class, 'store'])->name('reservations.store');

    Route::get('/reservations/select_tour/review', [ ReservationController::class, 'selectTourBeforeReview' ])->name('reservations.select.tour.review');
    Route::get('/reservations/review_tour', [ ReservationController::class, 'reviewTour' ])->name('reservations.tour.review');
    Route::get('/reservations/{reservation}', [ ReservationController::class, 'show'])->name('reservations.show');
    Route::delete('/reservations/{reservation}', [ ReservationController::class, 'destroy'])->name('reservations.destroy');
});

Route::get('/pdf-test', function(){
    //$pdf = App::make('dompdf.wrapper');
    $pdf = PDF::loadView('pdfs.pdf_test');
    //$pdf->loadView('pdfs.pdf_test');
    return $pdf->stream();
});



require __DIR__.'/auth.php';

app/Models/Tour.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tour extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'cost_kids',
        'cost_adults',
        'cost_elders',
        'limit',
        'active',
        'company_id',
    ];

    function departures() {
        return $this->hasMany(Departure::class);
    }

    function hasEnabledDepartures() {
        $count = Departure::where('tour_id', $this->id)->where('closed',false)->get();

        return count($count) > 0 ? true : false;
    }

    function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tour;
use App\Models\Company;
use Illuminate\Http\Request;

class TourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tours.index', [
            'tours' => Tour::paginate(20),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tours.create', [
            'companies' => Company::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|min:4',
            'cost_kids' => 'required|numeric|min:0',
            'cost_adults' => 'required|numeric|min:0',
            'cost_elders' => 'required|numeric|min:0',
            'cost_elders' => 'required|numeric|min:0',
            'company_id' => 'required',
        ]);

        Tour::create($request->all());

        return redirect()
                ->route('tours.index')
                ->with('green', '¡Tour agregado!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function show(Tour $tour)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function edit(Tour $tour)
    {
        return view('tours.edit', [
            'tour' => $tour,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tour $tour)
    {
        $validated = $request->validate([
            'name' => 'required|min:4',
            'cost_kids' => 'required|numeric|min:0',
            'cost_adults' => 'required|numeric|min:0',
            'cost_elders' => 'required|numeric|min:0',
        ]);

        $tour->name = $request->name;
        $tour->cost_kids = $request->cost_kids;
        $tour->cost_adults = $request->cost_adults;
        $tour->cost_elders = $request->cost_elders;
        $tour->active = $request->has('active') ? true : false;
        $tour->is_fast = $request->has('is_fast') ? true : false;
        $tour->limit = $request->limit;

        $tour->save();

        return redirect()
                ->route('tours.index')
                ->with('yellow', '¡Tour actualizado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tour $tour)
    {
        $tour->delete();

        return redirect()
                ->route('tours.index')
                ->with('red', '¡Tour borrado!');
    }
}

app/Http/Controllers/ZoneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Zone;
use Illuminate\Http\Request;

class ZoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('zones.index', [
            'zones' => Zone::withCount('hotels')->paginate(25),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('zones.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|min:4',
            'number' => 'required|unique:zones',
            'closure' => 'required',
        ]);

        $zone = Zone::create($validated);

        return redirect()
                ->route('zones.index')
                ->with('green', '¡Zona añadida!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function show(Zone $zone)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function edit(Zone $zone)
    {
        return view('zones.edit', [
            'zone' => $zone,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Zone $zone)
    {
        $request->validate([
            'name' => 'required|min:4',
            'closure' => 'required',
        ]);

        $zone->name = $request->name;
        $zone->closure = $request->closure;
        $zone->save();

        return redirect()
                ->route('zones.index')
                ->with('yellow', '¡Zona actulizada!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Zone  $zone
     * @return \Illuminate\Http\Response
     */
    public function destroy(Zone $zone)
    {
        $zone->delete();
        return redirect()
                ->route('zones.index')
                ->with('red', '¡Zona borrada!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/tours/create.blade.php
<x-app-layout>

    <div class="subtitle-header">
        <h4>
            Agregar Hotel
        </h4>
    </div>

    <div class="ui container page-description">
        <p>
            Usa esta seccion para agregar un hotel
        </p>
        @if ($errors->any())
            <div class="ui message warning">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <div class="ui container main">

        <form class="ui form" method="post" action="{{ route('tours.store') }}">
            @csrf
            <div class="field">
                <label>Nombre</label>
                <input type="text" name="name" placeholder="Nombre del tour" value="{{ old('name') }}">
            </div>
            <div class="field">
                <label>Precio niños</label>
                <input type="number" name="cost_kids" placeholder="Precio niños" value="{{ old('cost_kids') }}">
            </div>
            <div class="field">
                <label>Precio adultos</label>
                <input type="number" name="cost_adults" placeholder="Precio adultos" value="{{ old('cost_adults') }}">
            </div>
            <div class="field">
                <label>Precio INSEN</label>
                <input type="number" name="cost_elders" placeholder="Precio INSEN" value="{{ old('cost_elders') }}">
            </div>
            <div class="field">
                <label>Límite (* No lo llenes si no tiene límite)</label>
                <input type="number" name="limit" placeholder="Límite de lugares, si es apicable" value="{{ old('limit') }}">
            </div>
            <div class="field">
                <label>Compañía</label>
                    <select class="ui fluid dropdown" name="company_id">
                        @forelse ($companies as $key => $company)
                            <option value="{{ $company->id }}">{{ $company->name }}</option>
                        @empty
                            <option class="ui message yellow" value="null">No hay compañías por el momento</option>
                        @endforelse
                    </select>
            </div>
            <button class="ui button purple" type="submit">Guardar</button>
        </form>

    </div>

</x-app-layout>

resources/views/tours/edit.blade.php
<x-app-layout>

    <div class="subtitle-header">
        <h4>
            Editar Tour
        </h4>
    </div>

    <div class="ui container page-description">
        {{-- <h4>
            Todos los usuarios en el sistema
        </h4> --}}
        <p>
            Usa esta seccion para editar el tour
        </p>
        @if ($errors->any())
            <div class="ui message warning">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @include('layouts.messages')
    </div>

    <div class="ui container main">

        <form class="ui form" method="post" action="{{ route('tours.update', ['tour' => $tour]) }}">
            @csrf
            @method('PUT')
            <div class="field">
                <label>Nombre</label>
                <input type="text" name="name" placeholder="Nombre" value="{{ $tour->name }}">
            </div>
            <div class="field">
                <label>Precio Niños</label>
                <input type="number" name="cost_kids" placeholder="Precio para niños" value="{{ $tour->cost_kids }}">
            </div>
            <div class="field">
                <label>Precio Adultos</label>
                <input type="number" name="cost_adults" placeholder="Precio para adultos" value="{{ $tour->cost_adults }}">
            </div>
            <div class="field">
                <label>Precio INSEN</label>
                <input type="number" name="cost_elders" placeholder="Precio para niños" value="{{ $tour->cost_elders }}">
            </div>
            <div class="field">
                <label>Límite</label>
                <input type="number" name="limit" placeholder="Límite" value="{{ $tour->limit }}">
            </div>
            <div class="field">
                <div class="ui checkbox">
                    <input type="checkbox" name="active" {{ $tour->active ? 'checked' : ''}}>
                    <label>Activo</label>
                </div>
            </div>
            @if ($tour->company->id == 2)
                <div class="field">
                    <div class="ui checkbox">
                        <input type="checkbox" name="is_fast" {{ $tour->is_fast ? 'checked' : ''}}>
                        <label>¿Fast Track?</label>
                    </div>
                </div>
            @endif
            <button class="ui button yellow" type="submit">Actualizar</button>
        </form>

    </div>

    <div class="ui main container">
        <h3>Horarios</h3>
        <div class="ui text-right">
            <a href="{{ route('departures.create') }}?tour={{$tour->id}}">
                <i class="fas fa-2x fa-plus-square"></i>&nbsp; Agregar horario
            </a>
        </div>
        <div class="spacer">
            <p>Da click en alguno para activarlo o desactivarlo</p>
            <ul>
                <li>Verde - activo</li>
                <li>Rojo - desactivado</li>
            </ul>
        </div>
        <div class="grid-departures">
            @forelse ($tour->departures->sortBy('hour') as $key => $departure)
                <div class="ui hour grey">
                    <a class="ui button {{ $departure->closed ? 'red' : 'green'}}" href="{{ route('departures.close', ['departure' => $departure]) }}" style="width: 80%;">
                        {{ $departure->hour }}
                    </a>
                    @if ( $tour->company->id == 2 )
                        <a href="#!" class="button ui purple action" id="modal{{ $departure->id }}" onclick="openModal({{ $departure->id }})" style="width:35%;">
                            <i class="fas fa-bus" style="color: white;"></i>
                                {{ $departure->type == 1 ? '51' : '61' }}
                        </a>
                    @endif
                    <a href="#!" class="button ui black action" id="modal{{ $departure->id }}" onclick="openModal({{ $departure->id }})">
                        <i class="fas fa-trash" style="color: white;"></i>
                    </a>
                </div>
            @empty
                <div class="ui message yellow">
                    No hay horarios para este tour
                </div>
            @endforelse
        </div>

    </div>
    @foreach ($tour->departures as $key => $departure)
        <div class="ui mini modal" id="{{ $departure->id }}">
            <div class="header">¿Borrar Horario?</div>
            <div class="content">
                <p>
                    {{ $departure->hour }}
                </p>
            </div>
            <div class="actions">
                <form action="{{ route('departures.destroy', ['departure'=>$departure]) }}" method="post" style="display: inline-block;">
                    @csrf
                    @method('delete')
                    <input type="submit" class="ui red button" value="¿Borrar?">
                </form>
                <div class="ui cancel purple button">Cancelar</div>
            </div>
        </div>
    @endforeach

    @push('scripts')
        <script type="text/javascript">

            $(document).ready( function() {
                $('.ui.mini.modal')
                .modal()
                ;
            });
            function openModal( id ){
                $('#'+id+'.ui.modal')
                  .modal('show')
                ;
            }
        </script>
    @endpush

</x-app-layout>

resources/views/tours/index.blade.php
<x-app-layout>

    <div class="subtitle-header">
        <h4>
            Admin Tours
        </h4>
    </div>

    <div class="ui container page-description">
        <h4>
            Todos los Tours en el sistema
        </h4>
        <p>
            Usa esta seccion para agregar o modificar tours
        </p>
        @include('layouts.messages')
    </div>

    <div class="ui container main">
        <div class="ui text-right">
            <a href="{{ route('tours.create') }}">
                <i class="fas fa-2x fa-plus-square"></i>
            </a>
        </div>
        <table class="ui yellow table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Precio Niños</th>
                    <th>Precio Adultos</th>
                    <th>Precio INSEN</th>
                    <th>Límite</th>
                    <th class="right aligned">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($tours as $key => $tour)
                    <tr class="{{ $tour->active ? '' : 'disabled'}}">
                        <td>
                            {{ $tour->name }}<br>
                            <small>
                                <b>({{ $tour->company->name }})</b>
                            </small>
                        </td>
                        <td>{{ $tour->cost_kids }}</td>
                        <td>{{ $tour->cost_adults }}</td>
                        <td>{{ $tour->cost_elders }}</td>
                        <td>{{ $tour->limit ? $tour->limit : 'N/A' }}</td>
                        <td class="right aligned" style="pointer-events: all;">
                            <a href="{{ route('tours.edit', ['tour' => $tour->id]) }}">
                                <i class="fas fa-2x fa-eye"></i>
                            </a>
                            {{-- @if ($zone->hotels_count == 0) --}}
                                <a href="#!" id="modal{{ $tour->id }}" onclick="openModal({{ $tour->id }})">
                                    <i class="fas fa-2x fa-trash-alt"></i>
                                </a>
                            {{-- @endif --}}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="10" class="ui message warning">
                            No hay tours en el sistema
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="ui container text text-center">
        {!! $tours->links('layouts.pagination') !!}
        {{-- {!! $zones->links() !!} --}}
    </div>

    @foreach ($tours as $key => $tour)
        <div class="ui mini modal" id="{{ $tour->id }}">
            <div class="header">¿Borrar Tour?</div>
            <div class="content">
                <p>
                    {{ $tour->name }}
                </p>
            </div>
            <div class="actions">
                <form action="{{ route('tours.destroy', ['tour'=>$tour]) }}" method="post" style="display: inline-block;">
                    @csrf
                    @method('delete')
                    <input type="submit" class="ui red button" value="¿Borrar?">
                </form>
                <div class="ui cancel purple button">Cancelar</div>
            </div>
        </div>
    @endforeach

    @push('scripts')
        <script type="text/javascript">

            $(document).ready( function() {
                $('.ui.mini.modal')
                .modal()
                ;
            });
            function openModal( id ){
                $('#'+id+'.ui.modal')
                  .modal('show')
                ;
            }
        </script>
    @endpush

</x-app-layout>